name: release-note

on:
  pull_request:
jobs:
  generate-release-notes-body:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: matsuri-tech/generate-release-notes-body-based-on-pull-requests@d75bba1db6f5c7d9038e0c026d4f37a4c30edbaa # v3.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_PREFIX: "Release Note"
