name: release-note

on:
  pull_request:
jobs:
  generate-release-notes-body:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: matsuri-tech/generate-release-notes-body-based-on-pull-requests@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_PREFIX: "Release Note"
