name: release-note

on:
  pull_request:
jobs:
  generate-release-notes-body:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: matsuri-tech/generate-release-notes-body-based-on-pull-requests@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_PREFIX: "Release Note"
